# Generated by Django 4.1.1 on 2022-11-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_at',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['title'], name='taskapp_tas_title_a11a54_idx'),
        ),
    ]
