# Generated by Django 4.1.1 on 2022-12-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_alter_task_due_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_at',
            field=models.DateField(default='2021-01-01'),
            preserve_default=False,
        ),
    ]
